### ISSUE TITLE
accessing YAML arrays

### ISSUE THREAD

**Issue by clausbertels** [picocms/Pico#406]
Hi guys,

I've been trying to access some data in the Front matter array using the percent syntax. I.e.:
```
social: 
 - link: myname@gmail.com
   icon: email.svg
 - link: http://www.instagram.com/myname
   icon: instagram.svg
 - link: http://www.linkedin.com/in/myname
   icon: linkedin.svg
```

How do I get the instagram link for example? I tried `%meta.social[1].link%` 

Thank you in advance.
