### ISSUE TITLE
Set mime type for template

### ISSUE THREAD

**Issue by raspbeguy** [picocms/Pico#544]
Hello,

I would like to know if there is a way to specify some HTTP properties, like the mime type.

AFAIC, I have a feed template that generates a RSS feed (I know there is a plugin for that, but I prefer the template way, mainly because I use a theme that does it that way). I with there would be a way to indicate that this template should use the header `Content-Type: application/rss+xml`.

**Comment by PhrozenByte** [comment]
You can't modify headers using Twig, you'll have to write a Pico plugin for that.

**Comment by raspbeguy** [comment]
I can imagine a dictionnary in the configuration enabling to specify various settings relative to certain templates, not only HTTP headers. For instance, title levels shift could be defined that way (see issue #543).
This could be like this:
```yaml
templatevars:
    post:
        type: text/html
        titleshift: 2
    feed:
        type: application/rss+xml
    default:
        [...]
```
