### ISSUE TITLE
Creating a new twig variable

### ISSUE THREAD

**Issue by notakoder** [picocms/Pico#616]
I wish to add some additional meta data for the .md pages inside the YAML header and access them in the twig template. How do I create twig variables in Pico and access them in templates?

**Comment by mayamcdougall** [comment]
lol, the simplest answer is that you can just *do* it.  Anything in the metadata can be accessed from that page's `meta` property (eg, `page.meta.your_variable`).  However, the problem you might notice is that this becomes case sensitive.  Writing it as `Your_Variable` in your YAML would require you to access it via `page.meta.Your_Variable`, not `page.meta.your_variable`.

To get around this, you can define your extra properties in a `pico-theme.yml` file in your theme folder.

Take a look at the [Default Theme's `pico-theme.yml`](https://github.com/picocms/pico-theme/blob/master/pico-theme.yml). 

```yml
meta:                         # Register meta headers used by this theme
  Logo: logo                  # The URL to your website's logo (value is passed to Pico's "url" Twig filter)
  Tagline: tagline            # Your website's tag line, shown right below your site title (supports Markdown)
  Social: social              # A list of social icons that will be shown in your website's footer;
```

You can think of the items you see under `meta` as aliases for your variables.  So, in the Default Theme, the `Logo:` property in your metadata is exposed in lowercase as `logo` (page.meta.logo) to the Twig template. (And they technically don't have to match, you can call each variable whatever you want internally).

Or even simpler I guess, left side YAML, right side Twig. 😂

Unfortunately, this aliasing only goes one layer deep (I'm in the habit of using a lot of nested variables in my themes, lol 😅), but it's good enough for most use cases.

You can actually just start with a copy of the Default Theme's `pico-theme.yml`  Change the `meta` parts, and omit the `widescreen` line, since that's just a config option the default theme uses.

For that matter, any theme configuration variables you create here can also be accessed via `config.theme_config`.  So in this example, the Default Theme uses `config.theme_config.widescreen` to determine if it should use a wider layout.
