### ISSUE TITLE
_meta use and abuse

### ISSUE THREAD

**Issue by vodkafilm** [picocms/Pico#631]
I'm trying to make my theme completely separate from the contents, taking a cue from the social links section, I used the _meta file to display some information (statistics and skills)
```
---
skill:
    - title:
      bar:
      icon:

stats:
    - title:
      count:
      icon:

social:
    - title: 
      url: 
      icon:

---
```
So in my twig page I have three for cycles `{% for var in pages["_meta"].meta.var %}` of course it works, but I was wondering if it was a correct use or to be avoided.
